const state={token:localStorage.getItem('sbhAdminToken')||'',data:null};
const $=s=>document.querySelector(s);
const fmt=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
async function api(url,opts={}){opts.headers={...(opts.headers||{}),'Content-Type':'application/json'};if(state.token)opts.headers.Authorization=`Bearer ${state.token}`;const r=await fetch(url,opts);let j={};try{j=await r.json()}catch{}if(r.status===401){logout(false);throw new Error('Session expired. Please login again.')}if(!r.ok)throw new Error(j.error||'Request failed');return j}
function showApp(){ $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');loadAll(); }
function logout(call=true){localStorage.removeItem('sbhAdminToken');state.token='';$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');if(call)location.reload()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{const j=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('#adminUser').value,password:$('#adminPass').value})});state.token=j.token;localStorage.setItem('sbhAdminToken',state.token);showApp()}catch(err){$('#loginError').textContent=err.message}});
$('#logoutBtn').addEventListener('click',()=>logout());
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`#${v}View`).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#pageTitle').textContent={dashboard:'Dashboard',rooms:'Room Inventory',bookings:'Bookings',payments:'Payments',settings:'Settings'}[v]||'Dashboard';if(v==='bookings')renderBookings();if(v==='payments')renderPayments();}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));
async function loadAll(){try{state.data=await api('/api/admin/dashboard');renderDashboard();renderRooms();renderBookings();renderPayments();$('#lastUpdated').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){if(state.token)alert(e.message)}}
function renderDashboard(){const d=state.data;$('#mTotal').textContent=d.totalRooms;$('#mAvailable').textContent=d.availableRooms;$('#mBooked').textContent=d.bookedRooms;$('#mBookings').textContent=d.bookings.length;$('#pRevenue').textContent=fmt(d.revenue);$('#pPaid').textContent=d.payments.filter(x=>x.status==='paid').length;$('#pPending').textContent=d.payments.filter(x=>x.status!=='paid').length;$('#dashRooms').innerHTML=groupsHtml(d.rooms);$('#recentBookings').innerHTML=d.bookings.slice(-6).reverse().map(bookingHtml).join('')||'<p class="muted">No bookings yet.</p>';}
function groupsHtml(groups){return Object.entries(groups).map(([cat,g])=>`<div class="room-group"><div class="room-group-head"><h4>${g.name} · ${fmt(g.price)}/night</h4><span class="tag ${g.available?'green':'red'}">${g.available} available / ${g.total}</span></div><div class="room-badges">${g.rooms.map(r=>`<span class="room-badge ${r.status}" title="${r.status}" onclick="quickStatus('${cat}','${r.number}')">${r.number} · ${r.status}</span>`).join('')}</div></div>`).join('')}
function renderRooms(){ $('#roomInventory').innerHTML=Object.entries(state.data.rooms).map(([cat,g])=>`<div class="room-group"><div class="room-group-head"><h4>${g.name}</h4><span class="tag ${g.available?'green':'red'}">${g.available} AVAILABLE</span></div><table class="room-table"><thead><tr><th>Room</th><th>Status</th><th>Rate</th><th>Action</th></tr></thead><tbody>${g.rooms.map(r=>`<tr><td><b>Room ${r.number}</b></td><td><span class="tag ${r.status==='available'?'green':r.status==='booked'?'red':'gold'}">${r.status.toUpperCase()}</span></td><td>${fmt(g.price)}</td><td><select class="status-select" onchange="changeStatus('${cat}','${r.number}',this.value)"><option ${r.status==='available'?'selected':''}>available</option><option ${r.status==='booked'?'selected':''}>booked</option><option ${r.status==='maintenance'?'selected':''}>maintenance</option></select></td></tr>`).join('')}</tbody></table></div>`).join('')}
async function changeStatus(cat,room,status){try{await api('/api/admin/rooms/status',{method:'POST',body:JSON.stringify({category:cat,room,status})});await loadAll()}catch(e){alert(e.message)}}
async function quickStatus(cat,room){const s=prompt(`Set Room ${room} status: available / booked / maintenance`,'available');if(!s||!['available','booked','maintenance'].includes(s))return;changeStatus(cat,room,s)}
function bookingHtml(b){return `<div class="booking-mini"><b>${b.bookingId}</b><div>${b.guestName} · Room ${b.room} · ${b.category}</div><small>${b.checkin} → ${b.checkout} · ${fmt(b.amount)} · <span class="tag ${b.paymentStatus==='paid'?'green':'gold'}">${b.paymentStatus}</span></small></div>`}
function renderBookings(){if(!state.data)return;const q=($('#bookingSearch')?.value||'').toLowerCase(),st=$('#bookingStatus')?.value||'all';let rows=state.data.bookings.filter(b=>(st==='all'||b.status===st)&&(!q||JSON.stringify(b).toLowerCase().includes(q)));$('#bookingRows').innerHTML=rows.slice().reverse().map(b=>`<tr><td><b>${b.bookingId}</b><br><small>${new Date(b.createdAt).toLocaleString()}</small></td><td>${b.guestName}<br><small>${b.phone}</small></td><td>${b.room}<br><small>${b.category}</small></td><td>${b.checkin}<br>${b.checkout}</td><td>${fmt(b.amount)}</td><td><span class="tag ${b.paymentStatus==='paid'?'green':'gold'}">${b.paymentStatus}</span>${b.paymentId?`<br><small>${b.paymentId}</small>`:''}</td><td><span class="tag ${b.status==='confirmed'?'green':b.status==='cancelled'?'red':'gold'}">${b.status}</span></td></tr>`).join('')||'<tr><td colspan="7" class="muted">No matching bookings.</td></tr>'}
$('#bookingSearch').addEventListener('input',renderBookings);$('#bookingStatus').addEventListener('change',renderBookings);
function renderPayments(){const p=state.data.payments||[];$('#paymentRows').innerHTML=p.slice().reverse().map(x=>`<tr><td>${x.paymentId||'—'}</td><td>${x.bookingId}</td><td>${x.room}</td><td>${fmt(x.amount)}</td><td><span class="tag ${x.status==='paid'?'green':'gold'}">${x.status}</span></td><td>${new Date(x.createdAt).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">No payment records.</td></tr>'}
$('#newBookingBtn').addEventListener('click',()=>{$('#bookingModal').classList.remove('hidden');populateManualRooms()});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#bookingModal').classList.add('hidden')));
function populateManualRooms(){const cat=$('#bCat').value,g=state.data.rooms[cat];$('#bRoom').innerHTML=g.rooms.filter(r=>r.status==='available').map(r=>`<option value="${r.number}">${r.number}</option>`).join('')||'<option value="">No available rooms</option>';$('#bAmount').value=g.price;}
$('#bCat').addEventListener('change',populateManualRooms);$('#manualBooking').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/admin/bookings',{method:'POST',body:JSON.stringify({guestName:$('#bGuest').value,phone:$('#bPhone').value,category:$('#bCat').value,room:$('#bRoom').value,checkin:$('#bIn').value,checkout:$('#bOut').value,amount:Number($('#bAmount').value),paymentStatus:$('#bPay').value})});$('#bookingModal').classList.add('hidden');e.target.reset();await loadAll();switchView('bookings')}catch(err){alert(err.message)}});
$('#saveSettings').addEventListener('click',async()=>{try{await api('/api/admin/settings',{method:'POST',body:JSON.stringify({name:$('#setName').value,whatsapp:$('#setWa').value,address:$('#setAddress').value,checkinTime:$('#setCheckin').value,checkoutTime:$('#setCheckout').value})});alert('Settings saved.')}catch(e){alert(e.message)}});
if(state.token)showApp();
